name: Go mod tidy
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: check
        run: |
          go mod download
          go mod tidy
          if ! git diff --exit-code
          then
            echo "Not go mod tidied"
            exit 1
          fi
