name: Coverage Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Run coverage
      run: go test ./pkgs/... -race -coverprofile=pkgs_coverage.out -covermode=atomic
    - uses: codecov/codecov-action@v3
      with:
        name: codecov-umbrella
        files: ./pkgs_coverage.out
        fail_ci_if_error: true 
        verbose: true 
